source 'https://rubygems.org'
source 'https://rails-assets.org'

ruby '2.1.1'

gem 'activeadmin', github: 'castequality/active_admin'
gem 'active_model_serializers'
gem 'airbrake'
gem 'asset_sync'
gem 'aws-sdk'
gem 'bigcartel', github: 'castequality/bigcartel'
gem 'bourbon'
gem 'coffee-rails'
gem 'compass-rails'
gem 'delayed_job_active_record', '>= 4.0.0'
gem 'dotenv-rails'
gem 'daemons'
gem 'dalli'
gem 'email_validator'
gem 'ember-rails'
gem 'ember-source', '1.7.0'
gem 'ember-data-source', '1.0.0.beta.10'
gem 'flexslider', github: 'castequality/Flexslider-2-Rails-Gem'
gem 'flutie'
gem 'google-analytics-rails'
gem 'high_voltage'
gem 'has_scope'
gem 'instagram'
gem 'jquery-rails'
gem 'jquery-turbolinks'
gem 'kaminari'
gem 'lightboxjs', github: 'castequality/lightboxjs'
gem 'memcachier'
gem 'naught'
gem 'neat'
gem 'pg'
gem 'paperclip'
gem 'rack-timeout'
gem 'rails', '>= 4.0.1'
gem 'rails-assets-ember-cloaking'
gem 'rails-assets-lodash'
gem 'rails-assets-moment'
gem 'rich', github: 'bastiaanterhorst/rich'
gem 'roman-numerals'
gem 'recipient_interceptor'
gem 'sass-rails'
gem 'simple_form'
gem 'tumblr_client'
gem 'turbolinks'
gem 'uglifier'
gem 'unicorn'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'foreman'
end

group :development, :test do
  gem 'factory_girl_rails'
  gem 'pry'
  gem 'rails-assets-jquery-mockjax'
  gem 'rspec-rails', '>= 2.14'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'spring-commands-teaspoon'
  gem 'teaspoon'
end

group :test do
  gem 'capybara-webkit'
  gem 'database_cleaner'
  gem 'json-schema'
  gem 'launchy'
  gem 'nokogiri', '1.6.3.1'
  gem 'shoulda-matchers'
  gem 'simplecov', require: false
  gem 'timecop'
  gem 'webmock'
end

group :staging, :production do
  gem 'newrelic_rpm', '>= 3.6.7'
  gem 'rails_12factor'
end
